services:
  web:
    image: videosvc:latest
    build: .
    ports:
      - "8000:8000"

    networks:
      - demo
    volumes:
      - test:/vms:ro

networks:
  demo:
    driver: bridge    

volumes:
  test:
    driver: local