# Generated by Django 5.1.4 on 2024-12-21 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_nickname_videofomats_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='max_duration',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='accounts',
            name='min_duration',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='max_file_size',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='videofomats',
            name='format',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
