# Generated by Django 5.1.4 on 2024-12-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_accounts_max_duration_accounts_min_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AccountFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.accounts')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanager.files')),
            ],
            options={
                'unique_together': {('account', 'file')},
            },
        ),
    ]
